function T2 = T_epcc_taylorized(q)
%T_EPCC_TAYLORIZED
%    T2 = T_EPCC_TAYLORIZED(B,E,K,L,T)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Mar-2022 10:41:43
in1 = q;
b = in1(4,:);
e = in1(2,:);
k = in1(3,:);
l = in1(1,:);
t = in1(5,:);

t2 = conj(e);
t3 = conj(l);
t4 = conj(t);
t5 = t2+1.0;
t6 = t3.^2;
t7 = t5.^2;
t8 = t3.*t4.*t5;
t9 = cos(t8);
t10 = sin(t8);
t11 = (b.*k.*t6.*t7.*t9)./2.0;
t12 = (b.*k.*t6.*t7.*t10)./2.0;
t13 = -t11;
T2 = reshape([t9-t12,t10+t13,b.*t3.*t5.*t9+k.*t3.*t5.*t10,0.0,-t10+t13,t9+t12,-b.*t3.*t5.*t10+k.*t3.*t5.*t9,0.0,-b.*t3.*t5,-k.*t3.*t5,1.0,0.0,b.*t6.*t7.*(-1.0./2.0),k.*t6.*t7.*(-1.0./2.0),t3.*t5,1.0],[4,4]);
