function T_2 = T_2(b_2,k_2,l_2,t_2)
%T_2
%    T_2 = T_2(B_2,K_2,L_2,t_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    09-Aug-2022 12:05:24

%Version: 1.1
t2 = l_2.^2;
t3 = 1.0./b_2;
t5 = 1.0./k_2;
t7 = 1.0./t_2;
t4 = t3.^2;
t6 = t5.^2;
t10 = t2.*t7;
t8 = t2.*t4;
t9 = t2.*t6;
t11 = cos(t10);
t12 = sin(t10);
t13 = t8+t9;
t14 = 1.0./t13;
t15 = sqrt(t13);
t16 = 1.0./t15;
t17 = l_2.*t15;
t18 = cos(t17);
t19 = sin(t17);
t20 = t18-1.0;
t21 = t9.*t14.*t20;
t24 = t2.*t3.*t5.*t11.*t14.*t20;
t25 = t2.*t3.*t5.*t12.*t14.*t20;
t22 = t21+1.0;
t23 = -t21;
t26 = t18+t23;
T_2 = reshape([t25+t11.*t22,t24+t12.*t26,-l_2.*t3.*t12.*t16.*t19-l_2.*t5.*t11.*t16.*t19,0.0,t24-t12.*t22,-t25+t11.*t26,-l_2.*t3.*t11.*t16.*t19+l_2.*t5.*t12.*t16.*t19,0.0,l_2.*t5.*t16.*t19,l_2.*t3.*t16.*t19,t18,0.0,-l_2.*t5.*t14.*t20,-l_2.*t3.*t14.*t20,t16.*t19,1.0],[4,4]);
