function g_1 = g_1(k_1,l_1)
%G_1
%    G_1 = G_1(K_1,L_1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 11:15:45

t2 = abs(k_1);
t3 = k_1.*l_1;
t4 = l_1.*t2;
t5 = cos(t3);
t7 = 1.0./t2;
t6 = sin(t4);
t8 = k_1.*t6.*t7;
g_1 = reshape([t5,0.0,-t8,0.0,0.0,1.0,0.0,0.0,t8,0.0,t5,0.0,-(t5-1.0)./k_1,0.0,t6.*t7,1.0],[4,4]);
