function g_2 = g_2(k_1,k_2,l_1,l_2)
%G_2
%    G_2 = G_2(K_1,K_2,L_1,L_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 11:15:46

t2 = abs(k_1);
t3 = abs(k_2);
t4 = k_1.*l_1;
t5 = k_2.*l_2;
t10 = 1.0./k_2;
t6 = l_1.*t2;
t7 = l_2.*t3;
t8 = cos(t4);
t9 = cos(t5);
t13 = 1.0./t2;
t14 = 1.0./t3;
t11 = sin(t6);
t12 = sin(t7);
t15 = t9-1.0;
t16 = t8.*t9;
t17 = k_1.*t9.*t11.*t13;
t18 = k_2.*t8.*t12.*t14;
t19 = k_1.*k_2.*t11.*t12.*t13.*t14;
t20 = -t19;
t21 = t16+t20;
g_2 = reshape([t21,0.0,-t17-t18,0.0,0.0,1.0,0.0,0.0,t17+t18,0.0,t21,0.0,-(t8-1.0)./k_1-t8.*t10.*t15+k_1.*t11.*t12.*t13.*t14,0.0,t11.*t13+t8.*t12.*t14+k_1.*t10.*t11.*t13.*t15,1.0],[4,4]);
