function J_1 = J_1(k_1,l_1)
%J_1
%    J_1 = J_1(K_1,L_1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 11:15:43

%Version: 1.1
t2 = abs(k_1);
t3 = sign(k_1);
t4 = k_1.*l_1;
t5 = l_1.*t2;
t7 = 1.0./t2;
t6 = sin(t5);
t8 = t7.^2;
t9 = cos(t5);
J_1 = reshape([1.0./k_1.^2.*(cos(t4)-1.0)+(l_1.*sin(t4))./k_1,0.0,-t3.*t6.*t8+l_1.*t3.*t7.*t9,0.0,t6.*t7-k_1.*t3.*t6.*t8+t3.*t4.*t7.*t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
