function T_1 = T_1(b_1,eps_1,k_1,l_1,t_1)
%T_1
%    T_1 = T_1(B_1,EPS_1,K_1,L_1,t_1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 11:15:05

%Version: 1.1
t2 = b_1.^2;
t3 = eps_1+1.0;
t4 = k_1.^2;
t5 = l_1.*t3.*t_1;
t8 = t2+t4;
t6 = cos(t5);
t7 = sin(t5);
t9 = 1.0./t8;
t10 = sqrt(t8);
t11 = 1.0./t10;
t12 = l_1.*t3.*t10;
t13 = cos(t12);
t14 = sin(t12);
t15 = t13-1.0;
t16 = t4.*t9.*t15;
t19 = b_1.*k_1.*t6.*t9.*t15;
t20 = b_1.*k_1.*t7.*t9.*t15;
t17 = -t16;
t18 = t16+1.0;
t21 = t13+t17;
T_1 = reshape([t20+t6.*t18,t19+t7.*t21,-b_1.*t7.*t11.*t14-k_1.*t6.*t11.*t14,0.0,t19-t7.*t18,-t20+t6.*t21,-b_1.*t6.*t11.*t14+k_1.*t7.*t11.*t14,0.0,k_1.*t11.*t14,b_1.*t11.*t14,t13,0.0,-k_1.*t9.*t15,-b_1.*t9.*t15,t11.*t14,1.0],[4,4]);
