function T_2 = T_2(b_2,eps_2,k_2,l_2,t_2)
%T_2
%    T_2 = T_2(B_2,EPS_2,K_2,L_2,t_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 11:15:05

%Version: 1.1
t2 = b_2.^2;
t3 = eps_2+1.0;
t4 = k_2.^2;
t5 = l_2.*t3.*t_2;
t8 = t2+t4;
t6 = cos(t5);
t7 = sin(t5);
t9 = 1.0./t8;
t10 = sqrt(t8);
t11 = 1.0./t10;
t12 = l_2.*t3.*t10;
t13 = cos(t12);
t14 = sin(t12);
t15 = t13-1.0;
t16 = t4.*t9.*t15;
t19 = b_2.*k_2.*t6.*t9.*t15;
t20 = b_2.*k_2.*t7.*t9.*t15;
t17 = -t16;
t18 = t16+1.0;
t21 = t13+t17;
T_2 = reshape([t20+t6.*t18,t19+t7.*t21,-b_2.*t7.*t11.*t14-k_2.*t6.*t11.*t14,0.0,t19-t7.*t18,-t20+t6.*t21,-b_2.*t6.*t11.*t14+k_2.*t7.*t11.*t14,0.0,k_2.*t11.*t14,b_2.*t11.*t14,t13,0.0,-k_2.*t9.*t15,-b_2.*t9.*t15,t11.*t14,1.0],[4,4]);
