function T_1 = T_1(b_1,k_1,l_1,t_1)
%T_1
%    T_1 = T_1(B_1,K_1,L_1,t_1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    05-Aug-2022 02:01:29

%Version: 1.1
t2 = l_1.*t_1;
t3 = b_1.^2;
t4 = k_1.^2;
t7 = 1.0./l_1;
t5 = cos(t2);
t6 = sin(t2);
t8 = t7.^2;
t9 = t3.*t8;
t10 = t4.*t8;
t11 = t9+t10;
t12 = 1.0./t11;
t13 = sqrt(t11);
t14 = 1.0./t13;
t15 = l_1.*t13;
t16 = cos(t15);
t17 = sin(t15);
t18 = t16-1.0;
t19 = t10.*t12.*t18;
t22 = b_1.*k_1.*t5.*t8.*t12.*t18;
t23 = b_1.*k_1.*t6.*t8.*t12.*t18;
t20 = t19+1.0;
t21 = -t19;
t24 = t16+t21;
T_1 = reshape([t23+t5.*t20,t22+t6.*t24,-b_1.*t6.*t7.*t14.*t17-k_1.*t5.*t7.*t14.*t17,0.0,t22-t6.*t20,-t23+t5.*t24,-b_1.*t5.*t7.*t14.*t17+k_1.*t6.*t7.*t14.*t17,0.0,k_1.*t7.*t14.*t17,b_1.*t7.*t14.*t17,t16,0.0,-k_1.*t7.*t12.*t18,-b_1.*t7.*t12.*t18,t14.*t17,1.0],[4,4]);
