function T_2 = T_2(b_2,k_2,l_1,l_2,t_2)
%T_2
%    T_2 = T_2(B_2,K_2,L_1,L_2,t_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    05-Aug-2022 02:01:30

%Version: 1.1
t2 = l_2.*t_2;
t3 = b_2.^2;
t4 = k_2.^2;
t7 = 1.0./l_1;
t5 = cos(t2);
t6 = sin(t2);
t8 = t7.^2;
t9 = t3.*t8;
t10 = t4.*t8;
t11 = t9+t10;
t12 = 1.0./t11;
t13 = sqrt(t11);
t14 = 1.0./t13;
t15 = l_2.*t13;
t16 = cos(t15);
t17 = sin(t15);
t18 = t16-1.0;
t19 = t10.*t12.*t18;
t22 = b_2.*k_2.*t5.*t8.*t12.*t18;
t23 = b_2.*k_2.*t6.*t8.*t12.*t18;
t20 = t19+1.0;
t21 = -t19;
t24 = t16+t21;
T_2 = reshape([t23+t5.*t20,t22+t6.*t24,-b_2.*t6.*t7.*t14.*t17-k_2.*t5.*t7.*t14.*t17,0.0,t22-t6.*t20,-t23+t5.*t24,-b_2.*t5.*t7.*t14.*t17+k_2.*t6.*t7.*t14.*t17,0.0,k_2.*t7.*t14.*t17,b_2.*t7.*t14.*t17,t16,0.0,-k_2.*t7.*t12.*t18,-b_2.*t7.*t12.*t18,t14.*t17,1.0],[4,4]);
