function G = G(E_1,E_2,Imx1,Imx2,gx,gz,k_1,k_2,l_1,l_2,m_1,m_2)
%G
%    G = G(E_1,E_2,Imx1,Imx2,GX,GZ,K_1,K_2,L_1,L_2,M_1,M_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    18-Jul-2022 18:11:58

t2 = abs(k_1);
t3 = abs(k_2);
t4 = sign(k_1);
t5 = sign(k_2);
t6 = k_1.*l_1;
t7 = k_2.*l_2;
t14 = 1.0./k_1;
t16 = 1.0./k_2;
t8 = l_1.*t2;
t9 = l_2.*t3;
t10 = cos(t6);
t11 = cos(t7);
t12 = sin(t6);
t13 = sin(t7);
t15 = t14.^2;
t17 = t16.^2;
t20 = 1.0./t2;
t22 = 1.0./t3;
t18 = sin(t8);
t19 = sin(t9);
t21 = t20.^2;
t23 = t22.^2;
t24 = cos(t8);
t25 = cos(t9);
t26 = t10-1.0;
t27 = t11-1.0;
G = [gx.*m_2.*(t15.*t26+l_1.*t12.*t14+l_1.*t12.*t16.*t27+t18.*t19.*t20.*t22-k_1.*t4.*t18.*t19.*t21.*t22+t4.*t6.*t19.*t20.*t22.*t24)+E_1.*Imx1.*k_1-gz.*m_2.*(t4.*t18.*t21-l_1.*t4.*t20.*t24+l_1.*t12.*t19.*t22-t16.*t18.*t20.*t27+k_1.*t4.*t16.*t18.*t21.*t27-t4.*t6.*t16.*t20.*t24.*t27)+gx.*m_1.*t15.*t26+gx.*l_1.*m_1.*t12.*t14-gz.*m_1.*t4.*t18.*t21+gz.*l_1.*m_1.*t4.*t20.*t24;gx.*m_2.*(t10.*t17.*t27+l_2.*t10.*t13.*t16-k_1.*t5.*t18.*t19.*t20.*t23+k_1.*l_2.*t5.*t18.*t20.*t22.*t25)-gz.*m_2.*(t5.*t10.*t19.*t23+k_1.*t17.*t18.*t20.*t27-l_2.*t5.*t10.*t22.*t25+k_1.*l_2.*t13.*t16.*t18.*t20)+E_2.*Imx2.*k_2];
