function T_2 = T_2(b_2,k_2,l_2,t_2)
%T_2
%    T_2 = T_2(B_2,K_2,L_2,t_2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Aug-2022 20:41:13

%Version: 1.1
t2 = l_2.*t_2;
t3 = b_2.^2;
t4 = k_2.^2;
t5 = cos(t2);
t6 = sin(t2);
t7 = t3+t4;
t8 = 1.0./t7;
t9 = sqrt(t7);
t10 = 1.0./t9;
t11 = l_2.*t9;
t12 = cos(t11);
t13 = sin(t11);
t14 = t12-1.0;
t15 = t4.*t8.*t14;
t18 = b_2.*k_2.*t6.*t8.*t14;
t19 = b_2.*k_2.*t5.*t8.*t14;
t16 = -t15;
t17 = t15+1.0;
t20 = t12+t16;
T_2 = reshape([t18+t5.*t17,t19+t6.*t20,-b_2.*t6.*t10.*t13-k_2.*t5.*t10.*t13,0.0,t19-t6.*t17,-t18+t5.*t20,-b_2.*t5.*t10.*t13+k_2.*t6.*t10.*t13,0.0,k_2.*t10.*t13,b_2.*t10.*t13,t12,0.0,-k_2.*t8.*t14,-b_2.*t8.*t14,t10.*t13,1.0],[4,4]);
